swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  
  /medicine/searchByName: 
   get: 
     tags: 
       - "Medicine instruction"
     description: "return medicine instruction "
     operationId: "searchMedicine"
     produces: 
       - "text"
     parameters: 
       - 
         name: "medicinename"
         in: "query"
         description: "latitude"
         required: false
         type: "string"
       
     responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Medicine'
        400:
          description: Invalid medicine name
         
        404:
          description: Medicine not found
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /hospital/searchbyKeyWord: 
   get: 
     tags: 
       - "Hospital Lists"
     description: "return hospital lists "
     operationId: "searchHospitals"
     produces: 
       - "text"
     parameters: 
       - 
         name: "KeyWord"
         in: "query"
         description: "latitude"
         required: false
         type: "string"
       
     responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/HospitalList'
        400:
          description: Invalid key word
         
        404:
          description: Hospital not found
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /patientreport/{reportid}: 
    get: 
     tags: 
       - "Patient Report"
     description: "gets air quality index"
     operationId: "viewPatientReport"
     produces: 
       - "text"
     parameters: 
       - 
         name: reportid
         in: path
         description: "longitude"
         required: true
         type: integer
         format: int64
     responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/PatientReport'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: 
        - "Patient Profile"
      description: 
        "create patient report"
      parameters:
        - 
         name: reportid
         in: path
         description: "longitude"
         required: true
         type: integer
         format: int64
        - name: task 
          in: body
          description: task object
          required: true
          schema:
            $ref: '#/definitions/PatientProfile'
      responses:
        200:
          description: Successful response
          schema:
              title: Return String
              type: string
              example: "Task added succesfully"
        500:
          description: Error
          schema: 
            type: string
            example: "Could not add Task"
            
  /patientreport/findByStatus: 
    get: 
     tags: 
       - "Patient Profile"
     description: "gets air quality index"
     operationId: "findby Status"
     produces: 
       - "text"
     parameters: 
       - 
         name: "medicinename"
         in: "query"
         description: "latitude"
         required: false
         type: "string"
     responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/PatientProfile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /patient:
    post:
      tags: 
        - "Patient Profile"
      description: 
        "create new patient profile"
      parameters:
        - name: task 
          in: body
          description: task object
          required: true
          schema:
            $ref: '#/definitions/PatientProfile'
      responses:
        200:
          description: Successful response
          schema:
              title: Return String
              type: string
              example: "Task added succesfully"
        500:
          description: Error
          schema: 
            type: string
            example: "Could not add Task"
            
  /patient/{patientid}: 
    get: 
     tags: 
       - "Patient Profile"
     description: "gets air quality index"
     operationId: "viewprofile"
     produces: 
       - "text"
     parameters: 
       - 
         name: patientid
         in: path
         description: "longitude"
         required: true
         type: integer
         format: int64
     responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/PatientProfile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: 
        - "Patient Profile"
      description: 
        "update new patient profile"
      parameters:
        - 
         name: patientid
         in: path
         description: "longitude"
         required: true
         type: integer
         format: int64
        - 
          name: task 
          in: body
          description: task object
          required: true
          schema:
            $ref: '#/definitions/PatientProfile'
      responses:
        200:
          description: Successful response
          schema:
              title: Return String
              type: string
              example: "Task added succesfully"
        500:
          description: Error
          schema: 
            type: string
            example: "Could not add Task"
            
  /patient/{patientid}/uploadImage: 
    post:
      tags: 
        - "Patient Profile"
      description: 
        "update new patient profile"
      parameters:
        - 
         name: patientid
         in: path
         description: "longitude"
         required: true
         type: integer
         format: int64
        - 
          name: file
          in: formData
          description: image file
          required: true
          type: file
      responses:
        200:
          description: Successful response
          schema:
              title: Return String
              type: string
              example: "Task added succesfully"
        500:
          description: Error
          schema: 
            type: string
            example: "Could not add Task"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions

definitions:
  Medicine:
    type: object
    properties:
      medicine_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      medicine_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
        
  PatientProfile:
    type: object
    properties:
      patient_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      patient_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
        
  PatientReport:
    type: object
    properties:
      patient_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      patient_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
        
  HospitalList:
    type: object
    properties:
      patient_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      patient_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
